intial commit for ceph-cosi-driver
ceph/ceph-cosi pull request #1
Opened 2021-06-04 13:07 UTC by thotz

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

2021-06-04 13:09 UTC, thotz commented
Currently creation of BAR are not working atm, https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/55

2021-06-04 13:14 UTC, leseb requested changes
Briefly review, thanks for all the work!

2021-06-04 13:14 UTC, leseb commented on LICENSE
> +   END OF TERMS AND CONDITIONS
Why is the `APPENDIX` missing?

2021-06-04 13:14 UTC, leseb commented on cmd/ceph-cosi-driver/cmd.go
> +// Copyright 2021 The Ceph-COSI Authors.
Use `/*`instead?

2021-06-04 13:14 UTC, leseb commented on pkg/util/s3client/s3-handlers.go
> +		return errors.Wrapf(err, "failed to create bucket %q", name)
I know Rook is using this `"github.com/pkg/errors"` package but to wrap an error you can just use the `fmt` package with the `%w` keyword instead.

2021-06-04 13:14 UTC, leseb commented on .gitignore
> +travis.yml
Why not using github actions?

2021-06-04 13:14 UTC, leseb commented on .gitignore
> +vendor
Are we vendoring?

2021-06-04 13:14 UTC, leseb commented on go.mod
> +	github.com/pkg/errors v0.9.1
based on my comment below I'd drop this package and just use `errors`.

2021-06-10 12:18 UTC, leseb requested changes

2021-06-10 12:18 UTC, leseb commented on cmd/ceph-cosi-driver/main.go
> +Licensed under the Apache License, Version 2.0 (the "License");
See cmd/ceph-cosi-driver/cmd.go

2021-06-10 12:18 UTC, leseb commented on pkg/driver/driver.go
> +Copyright 2021 The Ceph-COSI Authors.
ditto see cmd/ceph-cosi-driver/cmd.go

2021-06-10 12:18 UTC, leseb commented on pkg/driver/driver.go
> +	radosgwapi "github.com/ceph/go-ceph/rgw/admin"
```suggestion
	rgwadmin "github.com/ceph/go-ceph/rgw/admin"
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/driver.go
> +	"github.com/thotz/cosi-driver-ceph/pkg/util/s3client"
What is this repo? Why is it not in the ceph org?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/driver.go
> +	//TODO : add support for TLS endpoint
+1

2021-06-10 12:18 UTC, leseb commented on pkg/driver/identityserver.go
> +		return nil, status.Error(codes.InvalidArgument, "ProvisionerName is empty")
```suggestion
		return nil, status.Error(codes.InvalidArgument, "Provisioner name is empty")
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/identityserver.go
> +Licensed under the Apache License, Version 2.0 (the "License");
ditto see cmd/ceph-cosi-driver/cmd.go

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +Licensed under the Apache License, Version 2.0 (the "License");
ditto see cmd/ceph-cosi-driver/cmd.go

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	radosgwapi "github.com/ceph/go-ceph/rgw/admin"
```suggestion
	rgwadmin "github.com/ceph/go-ceph/rgw/admin"
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	radosgwAdminClient *radosgwapi.API
```suggestion
	rgwAdminClient *radosgwapi.API
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	S3Client           *s3client.S3Agent
Does it need to be exported?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	klog.Info("Using ceph rgw to create Backend Bucket")
```suggestion
	klog.Info("Using Ceph RADOS Gateway to create Backend Bucket")
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.ErrorS(fmt.Errorf("Invalid Argument"), "Protocol is nil")
Is `Invalid Argument` the most appropriate error?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.ErrorS(fmt.Errorf("Invalid Argument"), "Protocol is nil")
Also please register these errors as variables like:

```go
var (
  errNilProtocol = errors.New("protocol is nil")
)

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.ErrorS(fmt.Errorf("Invalid Argument"), "S3 protocol is nil")
ditto use register the error in an errors.go file?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	klog.V(3).InfoS("Create Bucket", "name", bucketName)
```suggestion
	klog.V(3).InfoS("Creating Bucket", "name", bucketName)
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.ErrorS(err, "Bucket creation failed")
```suggestion
		klog.ErrorS(err, "failed to create bucket")
```

Also pass the `bucketName`?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	klog.Infof("Delete bucket %q", req.GetBucketId())
```suggestion
	klog.Infof("Deleting bucket %q", req.GetBucketId())
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.Info("failed to delete bucket %q", req.GetBucketId())
```suggestion
		klog.ErrorS("failed to delete bucket %q", req.GetBucketId())
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		return nil, status.Error(codes.Internal, "Bucket deletion failed")
`failed to`

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	user, err := s.radosgwAdminClient.CreateUser(context.Background(), radosgwapi.User{
Why not passing `ctx` instead of a new one?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.Error("failed to create user", err)
Should we check for `UserAlreadyExists`?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	klog.Infof("set policy %v", out)
is it intended?

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		Credentials: fmt.Sprintf("[default]\naws_access_key %s\naws_secret_key %s", user.Keys[0].AccessKey, user.Keys[0].SecretKey),
A function will do nice instead. To return the credentials

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +	klog.Infof("Delete user %q", req.GetAccountId())
```suggestion
	klog.Infof("Deleting user %q", req.GetAccountId())
```

2021-06-10 12:18 UTC, leseb commented on pkg/driver/provisioner.go
> +		klog.Error("falied to Revoke Bucket Access")
```suggestion
		klog.Error("failed to Revoke Bucket Access")
```

2021-06-10 12:18 UTC, leseb commented on pkg/util/s3client/policy.go
> +Copyright 2021 The Ceph-COSI Authors.
ditto see cmd/ceph-cosi-driver/cmd.go

2021-06-10 12:18 UTC, leseb commented on pkg/util/s3client/policy.go
> +// //////////////
let's remove this

2021-06-10 12:18 UTC, leseb commented on pkg/util/s3client/s3-handlers.go
> +Copyright 2021 The Ceph-COSI Authors.
ditto see cmd/ceph-cosi-driver/cmd.go

2021-06-11 12:51 UTC, thotz commented on CONTRIBUTING.md
> +Welcome to Kubernetes. We are excited about the prospect of you joining our [community](https://git.k8s.io/community)! The Kubernetes community abides by the CNCF [code of conduct](code-of-conduct.md
removed this file for the time being

2021-06-11 12:53 UTC, thotz commented on cmd/ceph-cosi-driver/cmd.go
> +	stringFlag(&SecretKey,
Yaa we need options for that, will address later

2021-06-11 12:54 UTC, thotz commented on pkg/driver/provisioner.go
> +	S3Client           *s3client.S3Agent
Nope

2021-06-11 13:26 UTC, leseb requested changes
few small nits

2021-06-11 13:26 UTC, leseb commented on pkg/driver/provisioner.go
> +
Let's log successful deletion.

2021-06-11 13:26 UTC, leseb commented on pkg/driver/provisioner.go
> +			return nil, status.Error(codes.Internal, "fetching policy failed")
failed to

2021-06-11 13:26 UTC, leseb commented on pkg/driver/provisioner.go
> +		return nil, status.Error(codes.Internal, "puting policy failed")
failed to

2021-06-11 13:26 UTC, leseb commented on pkg/driver/provisioner.go
> +		return nil, status.Error(codes.Internal, "falied to Revoke Bucket Access")
failed to

2021-07-01 12:07 UTC, leseb approved these changes

2021-07-01 12:07 UTC, leseb commented
@thotz I don't see any gh action yet but I see you added a `make`? Is it planned in another PR?

2021-07-01 12:58 UTC, thotz commented
> @thotz I don't see any gh action yet but I see you added a `make`? Is it planned in another PR?

I just added `make` file building container image, no test cases or gh actions added till now. Will add as separate PR

2021-07-01 13:04 UTC, leseb commented
> > @thotz I don't see any gh action yet but I see you added a `make`? Is it planned in another PR?
> 
> I just added `make` file building container image, no test cases or gh actions added till now. Will add as separate PR

Sounds, anything else before I merge this?

2021-07-01 13:59 UTC, thotz commented
> > > @thotz I don't see any gh action yet but I see you added a `make`? Is it planned in another PR?
> > 
> > 
> > I just added `make` file building container image, no test cases or gh actions added till now. Will add as separate PR
> 
> Sounds good`, anything else before I merge this?

This can be base for the next set of work, it defines all the existing APIs provided by the COSI(still need to improve)

2021-07-01 14:04 UTC, merged